language: minimal

dist: xenial

before_script:
  - make install-ssh

script:
  - make mirror
  - make rebase-and-push BRANCH=enable-ci
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - make build-image
